name: online_ticked
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  go_router: ^14.2.0
  flex_color_scheme: ^7.3.1
  firebase_auth: ^5.1.1
  firebase_messaging: ^15.0.2
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  firebase_database: ^11.0.2
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  firebase_storage: ^12.1.0
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  pdf: ^3.11.0
  printing: ^5.13.1
  flutter_launcher_icons: ^0.13.1
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  flutter_pdfview: ^1.3.2
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon/image.png"
    background_color: "#ffffff"
    theme_color: "#faf333"

flutter:




  uses-material-design: true



  assets:
    - assets/app_icon/
    - assets/logo/
    - assets/images/
    - assets/font/tr.ttf










