// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA04FSp2ok5YDt4pBR0PpQy5Qag7mBrkB0',
    appId: '1:347800906816:web:969bb6d08f5992a25743a5',
    messagingSenderId: '347800906816',
    projectId: 'online-ticket-44438',
    authDomain: 'online-ticket-44438.firebaseapp.com',
    databaseURL: 'https://online-ticket-44438-default-rtdb.firebaseio.com',
    storageBucket: 'online-ticket-44438.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJspThwW2Xn_qBdJhKzJGIphZm7ChFT1Y',
    appId: '1:347800906816:android:52b12f8753e61ba65743a5',
    messagingSenderId: '347800906816',
    projectId: 'online-ticket-44438',
    databaseURL: 'https://online-ticket-44438-default-rtdb.firebaseio.com',
    storageBucket: 'online-ticket-44438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5OkLAI4d9V8p2EWU4zpWnzvVaKV9hVR8',
    appId: '1:347800906816:ios:3c123da29d368e905743a5',
    messagingSenderId: '347800906816',
    projectId: 'online-ticket-44438',
    databaseURL: 'https://online-ticket-44438-default-rtdb.firebaseio.com',
    storageBucket: 'online-ticket-44438.appspot.com',
    iosBundleId: 'com.firesoft.onlineTicked',
  );
}
